language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - cd ./client
  - yarn
  - yarn build

script:
  # script默认是npm test，如果有yarn.lock文件则会用yarn test
  # 参考：https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
  - echo "Skipping tests"

deploy:
  # github pages部署的相关参数页面
  # https://docs.travis-ci.com/user/deployment/pages/
  provider: pages
  skip-cleanup: true
  # 默认是当前repo仓库，如果需要提交到别的仓库则需要设置repo的值
  repo: pkjy/pkjy.github.io
  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  github-token: $GITHUB_ACCESS_TOKEN 
  target-branch: master
  # 是否保存提交记录
  # keep-history: true
  local-dir: client/dist
  on:
    branch: master