<template>
  <section>
      <app-logo/>
      <section class="main-content">
          <h3 id="poster">海报</h3>
          <img src="~assets/images/海报一-w500-min.png">
          <img src="~assets/images/海报二-w500-min.png">
          <h3>lovewins-LOGO</h3>
          <img src="~assets/images/横着彩色LOGO-w500-min.png">
          <img src="~assets/images/竖着彩色LOGO-w500-min.png">
          <h3>请柬</h3>
          <img src="~assets/images/请柬-w500-min.png">
          <img src="~assets/images/请柬2-w500-min.png">
          <h3 id="leaflets">传单</h3>
          <img src="~assets/images/商家传单-w500-min.png">
          <img src="~assets/images/宣传单正面-w500-min.png">
          <img src="~assets/images/宣传单背面-w500-min.png">
          <footer class="site-footer">
              <span class="site-footer-credits">This page was generated by <a href="http://pkjy.github.io/"><i class="fa fa-certificate fa-spin"></i>pkjy<i class="fa fa-certificate fa-spin"></i></a>.</span>
          </footer>
      </section>
  </section>
</template>

<script>
import AppLogo from "~/components/AppLogo.vue"

export default {
  components: {
    AppLogo
  }
}
</script>

<style>

</style>
